### ISSUE TITLE
[报错]无法启动

### ISSUE THREAD

**Issue by Agnes4m** [joeyHXD/dota2_watcher_bot#4]
已填写api在第一次启动正常使用后，重启就无法启动了
```

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\bot\HoshinoBot\hoshino\service.py", line 349, in wrapper
    ret = await func()
  File "C:\bot\HoshinoBot\hoshino\modules\dota2_watcher_bot\run.py", line 71, in update
    msg,new_update = get_message_DOTA2(players)
  File "C:\bot\HoshinoBot\hoshino\modules\dota2_watcher_bot\common.py", line 35, in get_message_DOTA2
    result = update_DOTA2(players)
  File "C:\bot\HoshinoBot\hoshino\modules\dota2_watcher_bot\common.py", line 15, in update_DOTA2
    match_id = DOTA2.get_last_match_id_by_short_steamID(player.short_steamID)
  File "C:\bot\HoshinoBot\hoshino\modules\dota2_watcher_bot\DOTA2.py", line 29, in get_last_match_id_by_short_steamID
    response = requests.get(url)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.steampowered.com', port=443): Max retries exceeded with url: /IDOTA2Match_570/GetMatchHistory/v001/?key=3CAD5CACAE770D1473BAEE31C064D478&account_id=440104839&matches_requested=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000000921F19C280>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

```

**Comment by joeyHXD** [comment]
我拿你的这个url试了，我能连得上，那应该不是api key的问题
你可以试试能不能登录这个网站
```
https://api.steampowered.com/IDOTA2Match_570/GetMatchHistory/v001/?key=3CAD5CACAE770D1473BAEE31C064D478&account_id=440104839&matches_requested=1
```
如果不行的话，建议通过代理服务器登录（刚更新了这个功能，你可以git pull一下）

**Comment by Agnes4m** [comment]
### 1、上方链接在服务器结果是这样（已经git pull过了）
![image](https://user-images.githubusercontent.com/70925546/199374213-87cc697e-d1fb-4fff-a3f5-066392fce70b.png)

### 2、启动状态下，经常会弹下面这个窗口，并且使得机器人整个暂时无响应。
似乎是每隔1-2分钟就自动更新一次，更新就卡主，卡主的表现在hoshino其他任何功能都无法响应，不过更新完成就好了
![image](https://user-images.githubusercontent.com/70925546/199374106-7a5329a2-7c57-464d-8385-3e5597d832aa.png)
![image](https://user-images.githubusercontent.com/70925546/199374413-a642e27b-7322-46f6-b9ae-6728472827d7.png)
### 3、昨天git pull前打一把是没有回应，今天更新后再试试看
（这战绩如果出来真的处刑了）

**Comment by joeyHXD** [comment]
是的，每隔60秒会更新一次这是正常的。你也可以去run.py里面，改成你觉得合适的更新频率。
然后```"Cannot get match history for a user that hasn't allowed it"```是因为你dota2隐藏了战绩，你可以下载个max+或者dotabuff之类的战绩app，按照他们那边的步骤取消隐藏战绩。
然后建议你去dota.py这个文件里面，添加一个代理服务器，这样应该会快一点。
我的服务器本来就在国外，所以倒是没遇到过这个问题（
